entry_ids = [
  { id = "ACE COMBAT 7: SKIES UNKNOWN", files = ["ACE COMBAT 7- SKIES UNKNOWN"] },
  { id = "AI: The Somnium Files", files = ["AI- The Somnium Files"] },
  { id = "Cities: Skylines", files = ["Cities- Skylines"] },
  { id = "Clair Obscur: Expedition 33", files = ["Clair Obscur- Expedition 33", "Clair Obscur-Expedition 33"] },
  { id = "DARK SOULS: REMASTERED", files = ["DARK SOULS™-REMASTERED"] },
  { id = "DARK SOULSⅡ: Scholar of the First Sin", files = ["DARK SOULS™Ⅱ-Scholar of the First Sin"] },
  { id = "Dead-End City: 死废城的少女", files = ["Dead-End City- 死废城的少女"] },
  { id = "ENDER LILIES: Quietus of the Knights", files = ["ENDER LILIES- Quietus of the Knights"] },
  { id = "ENDER MAGNOLIA: Bloom in the Mist", files = ["ENDER MAGNOLIA- Bloom in the Mist"] },
  { id = "The Expanse: Osiris Reborn", files = ["The Expanse- Osiris Reborn"] },
  { id = "Fate/Samurai Remnant", files = ["Fate_Samurai Remnant"] },
  { id = "Fate/stay night", files = ["Fate_stay night"] },
  { id = "光明记忆：无限", files = ["光明记忆- 无限"] },
  { id = "Hollow Knight: Silksong", files = ["Hollow Knight- Silksong", "Hollow Knight-Silksong"] },
  { id = "Kingdom Come: Deliverance II", files = ["Kingdom Come- Deliverance II"] },
  { id = "Monster Hunter: World", files = ["Monster Hunter-World"] },
  { id = "NieR: Automata", files = ["NieR-Automata™"] },
  { id = "Plants vs. Zombies: GOTY Edition", files = ["Plants vs. Zombies- GOTY Edition"] },
  { id = "PUBG: BATTLEGROUNDS", files = ["PUBG-BATTLEGROUNDS"] },
  { id = "Sekiro: Shadows Die Twice", files = ["Sekiro™-Shadows Die Twice"] },
]
