akas = [
  { id = "R.E.P.O.", akas = [] },
  { id = "Rance Ⅸ -ヘルマン革命-", akas = ["兰斯9：赫尔曼革命"] },
  { id = "Rance Ⅹ -決戦-", akas = ["兰斯10：决战"] },
  { id = "Rance02 -反逆の少女たち-", akas = ["兰斯2：反叛的少女们"] },
  { id = "Rance03 -リーザス陥落-", akas = ["兰斯03：利萨斯陷落"] },
]
