akas = [
  { id = "爱与机器人维修技术", akas = ["All Our Broken Parts"] },
  { id = "穢翼のユースティア", akas = ["秽翼的尤斯蒂娅"] },
  { id = "アルミオシオンの医術師", akas = ["阿尔米奥西翁的医术师"] },
  { id = "被虐のノエル", akas = ["被虐的诺艾尔"] },
  { id = "媚肉の香り～ネトリネトラレヤリヤラレ～", akas = ["媚肉之香"] },
  { id = "苍翼：混沌效应", akas = ["BlazBlue Entropy Effect"] },
  { id = "戴森球计划", akas = ["Dyson Sphere Program"] },
  { id = "动物迷城", akas = ["Back to the Dawn"] },
  { id = "ダンガンロンパ3 -The End of 希望ヶ峰学園-", akas = ["新枪弹辩驳V3 大家自相残杀的新学期"] },
  { id = "ドーナドーナ いっしょにわるいことをしよう", akas = ["多娜多娜 一起来干坏事吧", "Dohna Dohna"] },
  { id = "(the) Gnorp Apologue", akas = ["糯米团子历代记"] },
  { id = "光明记忆：无限", akas = ["Bright Memory: Infinite"] },
  { id = "逆転裁判123 成歩堂セレクション", akas = ["逆转裁判123", "Phoenix Wright: Ace Attorney Trilogy"] },
  { id = "黑神话：悟空", akas = ["Black Myth: Wukong"] },
  { id = "谜月旅途", akas = ["Honeymoon : Mystery Journey"] },
  { id = "明末：渊虚之羽", akas = ["WUCHANG: Fallen Feathers"] },
  { id = "明日方舟", akas = ["Arknight"] },
  { id = "明日方舟：终末地", akas = ["Endfield"] },
  { id = "もんむす·くえすと！", akas = ["勇者大战魔物娘", "勇战"] },
  { id = "三色绘恋", akas = ["Tricolor Lovestory"] },
  { id = "社群审查", akas = ["The Censor"] },
  { id = "死神模拟器", akas = ["Trainee Death Simulator"] },
  { id = "ツヴァイ!!2", akas = ["双星物语2"] },
  { id = "文字规则怪谈", akas = ["Myths of Rules"] },
  { id = "文字游戏", akas = ["Word Game"] },
  { id = "无限机兵", akas = ["AI LIMIT"] },
  { id = "犹格索托斯的庭院", akas = ["Yog-Sothoth's Yard"] },
  { id = "再见", akas = ["Once Again"] },
  { id = "ゼルダの伝説 ブレス オブ ザ ワイルド", akas = ["塞尔达传说 旷野之息", "The Legend of Zelda: Breath of the Wild", "野炊"] },
]
