[title_names]

"Bloodstained: Ritual of the Night" = ["Bloodstained- Ritual of the Night"]
"Bloodstained: The Scarlet Engagement" = ["Bloodstained- The Scarlet Engagement"]

"ENDER LILIES: Quietus of the Knights" = ["ENDER LILIES- Quietus of the Knights"]
"ENDER MAGNOLIA: Bloom in the Mist" = ["ENDER MAGNOLIA- Bloom in the Mist"]

"Hollow Knight: Silksong" = ["Hollow Knight- Silksong", "Hollow Knight-Silksong"]

"Sheepy: A Short Adventrue" = ["Sheepy- A Short Adventrue"]
