[title_names]

"ACE COMBAT 7: SKIES UNKNOWN" = ["ACE COMBAT 7- SKIES UNKNOWN"]
"AI: The Somnium Files" = ["AI- The Somnium Files"]

"Cities: Skylines" = ["Cities- Skylines"]
"Clair Obscur: Expedition 33" = ["Clair Obscur- Expedition 33", "Clair Obscur-Expedition 33"]

"DARK SOULS™: REMASTERED" = ["DARK SOULS™-REMASTERED"]
"DARK SOULS™Ⅱ: Scholar of the First Sin" = ["DARK SOULS™Ⅱ-Scholar of the First Sin"]
"Dead-End City: 死废城的少女" = ["Dead-End City- 死废城的少女"]

"ENDER LILIES: Quietus of the Knights" = ["ENDER LILIES- Quietus of the Knights"]
"ENDER MAGNOLIA: Bloom in the Mist" = ["ENDER MAGNOLIA- Bloom in the Mist"]
"The Expanse: Osiris Reborn" = ["The Expanse- Osiris Reborn"]

"Fate/Samurai Remnant" = ["Fate_Samurai Remnant"]
"Fate/stay night" = ["Fate_stay night"]

"光明记忆：无限" = ["光明记忆- 无限"]

"Hollow Knight: Silksong" = ["Hollow Knight- Silksong", "Hollow Knight-Silksong"]

"Kingdom Come: Deliverance II" = ["Kingdom Come- Deliverance II"]

"Monster Hunter: World" = ["Monster Hunter-World"]

"NieR: Automata" = ["NieR-Automata™"]

"Plants vs. Zombies: GOTY Edition" = ["Plants vs. Zombies- GOTY Edition"]
"PUBG: BATTLEGROUNDS" = ["PUBG-BATTLEGROUNDS"]

"Sekiro: Shadows Die Twice" = ["Sekiro™-Shadows Die Twice"]
