[tag_types.1]
"游戏" = [
  "ARPG",
  "类银河城+类银恶",
  "平台跳跃",
  "指向点击",
  "策略+SLG",
  "视觉小说",
  "JRPG",
  "Rougelike",
  "塔防",
  "格斗",
  "沙盒",
  "二游",
  "AVG+冒险",
  "ACT+动作",
  "RTS+即时战略",
  "射击+FPS+TPS",
  "清版",
]
"动漫" = [
  "漫改",
  "小说改+轻改",
]
"书籍" = [
  "文集+短篇集+随笔集",
  "改编",
  "经典补完计划",
  "科幻",
  "奇幻",
  "轻小说",
  "网文",
  "文学",
]

[tag_types.2]
"游戏" = [
  "模拟经营",
  "像素",
  "回合制",
  "解谜",
  "类魂",
  "卡牌",
  "箱庭",
  "剧情",
  "线性",
  "养成",
]
"动漫" = [
  "校园",
  "日常",
  "架空",
  "战斗",
]
"书籍" = [
  "单元剧",
  "公路片",
  "架空",
  "历史",
  "冒险",
  "日常",
  "太空歌剧",
  "童话",
  "推理",
  "现实主义",
  "自然+动物",
  "恋爱",
  "恐怖",
]

[tag_types.3]
"游戏" = [
  "Metagame",
  "放置",
  "末日",
  "物理",
  "派对",
  "知识锁",
]
"动漫" = []
"书籍" = [
  "地外生命",
  "后宫",
  "机甲",
  "梦想",
  "末世",
  "青春",
  "人体改造",
  "时间回溯",
  "时间旅行",
  "校园",
  "星际航行",
  "星际战争",
  "异世界",
  "穿越",
  "战斗",
  "志怪",
  "种田",
]
