aka = [
  { id = "100% Orange Juice", names = ["100%鲜橙汁"] },
  { id = "14种扫雷变体", names = ["14 Minesweeper Variants"] },
  { id = "14种扫雷变体 2", names = ["14 Minesweeper Variants 2"] },
  { id = "ACE COMBAT 7: SKIES UNKNOWN", names = ["皇牌空战7：未知空域"] },
  { id = "AI: The Somnium Files", names = ["AI：梦境档案"] },
  { id = "Alabaster Dawn", names = ["皓白初晓"] },
  { id = "ANIMAL WELL", names = ["动物井"] },
  { id = "Another Crab's Treasure", names = ["蟹蟹寻宝奇遇"] },
  { id = "ARK: Survival Evolved", names = ["方舟：生存进化"] },
  { id = "ARMORED CORE VI FIRES OF RUBICON", names = ["装甲核心 VI 境界天火"] },
  { id = "Artis Impact", names = ["爱氏物语"] },
  { id = "ASTLIBRA ～生きた証～ Revision", names = ["神之天平"] },
  { id = "Axiom Verge", names = ["公理边缘"] },
  { id = "爱与机器人维修技术", names = ["All Our Broken Parts"] },
  { id = "穢翼のユースティア", names = ["秽翼的尤斯蒂娅"] },
  { id = "アルミオシオンの医術師", names = ["阿尔米奥西翁的医术师"] },
  { id = "Balatro", names = ["小丑牌"] },
  { id = "Baldur's Gate 3", names = ["博德之门3"] },
  { id = "Besiege", names = ["围攻"] },
  { id = "The Binding of Isaac: Rebirth", names = ["以撒的结合：重生"] },
  { id = "BLACK SOULS", names = [] },
  { id = "BLACK SOULS -黒の童話と五魔姫-", names = ["BLACK SOULS -黑童话与五魔姬-"] },
  { id = "Blasphemous", names = ["神之亵渎"] },
  { id = "Blasphemous 2", names = ["神之亵渎2"] },
  { id = "Bleak Sword DX", names = ["荒绝之剑DX"] },
  { id = "Bloodstained: Ritual of the Night", names = ["赤痕：夜之仪式"] },
  { id = "Bloodstained: The Scarlet Engagement", names = ["赤痕：绯红誓约"] },
  { id = "被虐のノエル", names = ["被虐的诺艾尔"] },
  { id = "媚肉の香り～ネトリネトラレヤリヤラレ～", names = ["媚肉之香"] },
  { id = "CATO: Buttered Cat", names = ["CATO 黄油猫"] },
  { id = "Celeste", names = ["蔚蓝"] },
  { id = "Chants of Sennaar", names = ["巴别塔圣歌"] },
  { id = "Cities: Skylines", names = ["城市：天际线"] },
  { id = "Clair Obscur: Expedition 33", names = ["光与影：33号远征队"] },
  { id = "COCOON", names = ["茧"] },
  { id = "CODE VEIN", names = ["噬血代码"] },
  { id = "Counter-Strike 2", names = ["反恐精英2"] },
  { id = "Craft the World", names = ["打造世界"] },
  { id = "Cris Tales", names = ["水晶传说"] },
  { id = "CrossCode", names = ["远星物语"] },
  { id = "Cultist Simulator", names = ["密教模拟器"] },
  { id = "Cuphead", names = ["茶杯头"] },
  { id = "Cyberpunk 2077", names = ["赛博朋克 2077", "赛博朋克2077"] },
  { id = "苍翼：混沌效应", names = ["BlazBlue Entropy Effect"] },
  { id = "草泥马历险记", names = [] },
  { id = "DARK SOULS: REMASTERED", names = ["黑暗之魂重制版"] },
  { id = "DARK SOULSⅡ: Scholar of the First Sin", names = ["黑暗之魂2：原罪学者"] },
  { id = "Darkest Dungeon", names = ["暗黑地牢"] },
  { id = "Dead Cells", names = ["死亡细胞"] },
  { id = "Dead-End City: 死废城的少女", names = ["Dead-End City Blues"] },
  { id = "戴森球计划", names = ["Dyson Sphere Program"] },
  { id = "动物迷城", names = ["Back to the Dawn"] },
  { id = "ダンガンロンパ3 -The End of 希望ヶ峰学園-", names = ["新枪弹辩驳V3 大家自相残杀的新学期"] },
  { id = "ドーナドーナ いっしょにわるいことをしよう", names = ["多娜多娜 一起来干坏事吧", "Dohna Dohna"] },
  { id = "Elden Ring", names = ["艾尔登法环"] },
  { id = "ELDEN RING", names = ["艾尔登法环"] },
  { id = "Elden Ring NightReign", names = ["艾尔登法环：黑夜君临"] },
  { id = "ELDEN RING NIGHTREIGN", names = ["艾尔登法环：黑夜君临", "黑环"] },
  { id = "ENDER LILIES: Quietus of the Knights", names = ["终焉之莉莉：骑士寂夜"] },
  { id = "ENDER MAGNOLIA: Bloom in the Mist", names = ["终焉之玛格诺利亚：雾中盛放之花"] },
  { id = "Escape the Backrooms", names = ["逃离后室"] },
  { id = "Eternum", names = ["永恒世界"] },
  { id = "Everlasting Summer", names = ["永恒之夏"] },
  { id = "The Expanse: Osiris Reborn", names = ["苍穹浩瀚：奥里西斯重生"] },
  { id = "Fate/Samurai Remnant", names = ["FSR"] },
  { id = "Fate/stay night", names = ["FSN"] },
  { id = "The Forest", names = ["森林"] },
  { id = "(the) Gnorp Apologue", names = ["糯米团子历代记"] },
  { id = "光明记忆：无限", names = ["Bright Memory: Infinite"] },
  { id = "逆転裁判123 成歩堂セレクション", names = ["逆转裁判123", "Phoenix Wright: Ace Attorney Trilogy"] },
  { id = "Hollow Knight", names = ["空洞骑士"] },
  { id = "Hollow Knight: Silksong", names = ["空洞骑士：丝之歌"] },
  { id = "How to Fish", names = ["渔力全开"] },
  { id = "Human Fall Flat", names = ["人类一败涂地"] },
  { id = "黑神话：悟空", names = ["Black Myth: Wukong"] },
  { id = "It Takes Two", names = ["双人成行"] },
  { id = "Kingdom Come: Deliverance II", names = ["天国：拯救2"] },
  { id = "LAB-Still Alive", names = [] },
  { id = "Leap Year", names = ["闰跃之年"] },
  { id = "Lethal Company", names = ["致命公司"] },
  { id = "Liar's Bar", names = ["骗子酒吧"] },
  { id = "LIMBO", names = ["地狱边境"] },
  { id = "Limbus Company", names = ["边狱巴士"] },
  { id = "Lobotomy Corporation - Monster Management Simulation", names = ["脑叶公司"] },
  { id = "Machinarium", names = ["机械迷城"] },
  { id = "Milk inside a bag of milk inside a bag of milk", names = ["牛奶袋内袋装牛奶"] },
  { id = "Minecraft", names = ["我的世界"] },
  { id = "Miside", names = ["米塔"] },
  { id = "Monster Hunter: World", names = ["怪物猎人：世界"] },
  { id = "Monument Valley", names = ["纪念碑谷"] },
  { id = "Monument Valley 2", names = ["纪念碑谷2"] },
  { id = "The Many Pieces of Mr. Coo", names = ["裂开了！裤先生"] },
  { id = "谜月旅途", names = ["Honeymoon : Mystery Journey"] },
  { id = "明末：渊虚之羽", names = ["WUCHANG: Fallen Feathers"] },
  { id = "明日方舟", names = ["Arknight"] },
  { id = "明日方舟：终末地", names = ["Endfield"] },
  { id = "もんむす·くえすと！", names = ["勇者大战魔物娘", "勇战"] },
  { id = "NieR: Automata", names = ["尼尔：机械纪元", "尼尔：自动人形"] },
  { id = "NUKITASHI", names = ["拔作岛"] },
  { id = "Ori and the Blind Forest", names = ["奥日与黑暗森林"] },
  { id = "Outer Wilds", names = ["星际拓荒"] },
  { id = "Persona 5 Royal", names = ["女神异闻录5皇家版"] },
  { id = "Plants vs. Zombies: GOTY Edition", names = ["植物大战僵尸：年度版"] },
  { id = "PUBG: BATTLEGROUNDS", names = ["绝地求生", "吃鸡"] },
  { id = "R.E.P.O.", names = [] },
  { id = "Rance Ⅸ -ヘルマン革命-", names = ["兰斯9：赫尔曼革命"] },
  { id = "Rance Ⅹ -決戦-", names = ["兰斯10：决战"] },
  { id = "Rance02 -反逆の少女たち-", names = ["兰斯2：反叛的少女们"] },
  { id = "Rance03 -リーザス陥落-", names = ["兰斯03：利萨斯陷落"] },
  { id = "Salt and Sanctuary", names = ["盐与避难所"] },
  { id = "Sekiro: Shadows Die Twice", names = ["只狼：影逝二度"] },
  { id = "SEQUEL blight", names = ["凋零余波"] },
  { id = "Slay the Spire", names = ["杀戮尖塔"] },
  { id = "Slay the Spire 2", names = ["杀戮尖塔2"] },
  { id = "Snakebird Complete", names = ["蛇鸟：完全版"] },
  { id = "Split Fiction", names = ["双影奇境"] },
  { id = "Starbound", names = ["星界边境"] },
  { id = "Stardew Valley", names = ["星露谷物语"] },
  { id = "三色绘恋", names = ["Tricolor Lovestory"] },
  { id = "社群审查", names = ["The Censor"] },
  { id = "死神模拟器", names = ["Trainee Death Simulator"] },
  { id = "Terraria", names = ["泰拉瑞亚"] },
  { id = "Touhou Luna Nights", names = ["东方月神夜"] },
  { id = "ツヴァイ!!2", names = ["双星物语2"] },
  { id = "Ultimate Chicken Horse", names = ["超级鸡马"] },
  { id = "Ultraman Fighting Evolution 3", names = ["奥特曼格斗进化3"] },
  { id = "VA-11 Hall-A Cyberpunk Bartender Action", names = ["赛博朋克酒保行动"] },
  { id = "Vampire Survivals", names = ["吸血鬼幸存者"] },
  { id = "文字规则怪谈", names = ["Myths of Rules"] },
  { id = "文字游戏", names = ["Word Game"] },
  { id = "无限机兵", names = ["AI LIMIT"] },
  { id = "犹格索托斯的庭院", names = ["Yog-Sothoth's Yard"] },
  { id = "ZORT", names = [] },
  { id = "再见", names = ["Once Again"] },
  { id = "ゼルダの伝説 ブレス オブ ザ ワイルド", names = ["塞尔达传说 旷野之息", "The Legend of Zelda: Breath of the Wild", "野炊"] },
]
