[[aka]]
id = "100% Orange Juice"
names = ["100%鲜橙汁"]

[[aka]]
id = "14种扫雷变体"
names = ["14 Minesweeper Variants"]

[[aka]]
id = "14种扫雷变体 2"
names = ["14 Minesweeper Variants 2"]

[[aka]]
id = "ACE COMBAT 7: SKIES UNKNOWN"
names = ["皇牌空战7：未知空域"]

[[aka]]
id = "AI: The Somnium Files"
names = ["AI：梦境档案"]

[[aka]]
id = "Alabaster Dawn"
names = ["皓白初晓"]

[[aka]]
id = "ANIMAL WELL"
names = ["动物井"]

[[aka]]
id = "Another Crab's Treasure"
names = ["蟹蟹寻宝奇遇"]

[[aka]]
id = "ARK: Survival Evolved"
names = ["方舟：生存进化"]

[[aka]]
id = "ARMORED CORE VI FIRES OF RUBICON"
names = ["装甲核心 VI 境界天火"]

[[aka]]
id = "Artis Impact"
names = ["爱氏物语"]

[[aka]]
id = "ASTLIBRA ～生きた証～ Revision"
names = ["神之天平"]

[[aka]]
id = "Axiom Verge"
names = ["公理边缘"]

[[aka]]
id = "爱与机器人维修技术"
names = ["All Our Broken Parts"]

[[aka]]
id = "穢翼のユースティア"
names = ["秽翼的尤斯蒂娅"]

[[aka]]
id = "アルミオシオンの医術師"
names = ["阿尔米奥西翁的医术师"]

[[aka]]
id = "Balatro"
names = ["小丑牌"]

[[aka]]
id = "Baldur's Gate 3"
names = ["博德之门3"]

[[aka]]
id = "Besiege"
names = ["围攻"]

[[aka]]
id = "The Binding of Isaac: Rebirth"
names = ["以撒的结合：重生"]

[[aka]]
id = "BLACK SOULS"
names = []

[[aka]]
id = "BLACK SOULS -黒の童話と五魔姫-"
names = ["BLACK SOULS -黑童话与五魔姬-"]

[[aka]]
id = "Blasphemous"
names = ["神之亵渎"]

[[aka]]
id = "Blasphemous 2"
names = ["神之亵渎2"]

[[aka]]
id = "Bleak Sword DX"
names = ["荒绝之剑DX"]

[[aka]]
id = "Bloodstained: Ritual of the Night"
names = ["赤痕：夜之仪式"]

[[aka]]
id = "Bloodstained: The Scarlet Engagement"
names = ["赤痕：绯红誓约"]

[[aka]]
id = "被虐のノエル"
names = ["被虐的诺艾尔"]

[[aka]]
id = "媚肉の香り～ネトリネトラレヤリヤラレ～"
names = ["媚肉之香"]

[[aka]]
id = "CATO: Buttered Cat"
names = ["CATO 黄油猫"]

[[aka]]
id = "Celeste"
names = ["蔚蓝"]

[[aka]]
id = "Chants of Sennaar"
names = ["巴别塔圣歌"]

[[aka]]
id = "Cities: Skylines"
names = ["城市：天际线"]

[[aka]]
id = "Clair Obscur: Expedition 33"
names = ["光与影：33号远征队"]

[[aka]]
id = "COCOON"
names = ["茧"]

[[aka]]
id = "CODE VEIN"
names = ["噬血代码"]

[[aka]]
id = "Counter-Strike 2"
names = ["反恐精英2"]

[[aka]]
id = "Craft the World"
names = ["打造世界"]

[[aka]]
id = "Cris Tales"
names = ["水晶传说"]

[[aka]]
id = "CrossCode"
names = ["远星物语"]

[[aka]]
id = "Cultist Simulator"
names = ["密教模拟器"]

[[aka]]
id = "Cuphead"
names = ["茶杯头"]

[[aka]]
id = "Cyberpunk 2077"
names = ["赛博朋克 2077", "赛博朋克2077"]

[[aka]]
id = "苍翼：混沌效应"
names = ["BlazBlue Entropy Effect"]

[[aka]]
id = "草泥马历险记"
names = []

[[aka]]
id = "DARK SOULS: REMASTERED"
names = ["黑暗之魂重制版"]

[[aka]]
id = "DARK SOULSⅡ: Scholar of the First Sin"
names = ["黑暗之魂2：原罪学者"]

[[aka]]
id = "Darkest Dungeon"
names = ["暗黑地牢"]

[[aka]]
id = "Dead Cells"
names = ["死亡细胞"]

[[aka]]
id = "Dead-End City: 死废城的少女"
names = ["Dead-End City Blues"]

[[aka]]
id = "戴森球计划"
names = ["Dyson Sphere Program"]

[[aka]]
id = "动物迷城"
names = ["Back to the Dawn"]

[[aka]]
id = "ダンガンロンパ3 -The End of 希望ヶ峰学園-"
names = ["新枪弹辩驳V3 大家自相残杀的新学期"]

[[aka]]
id = "ドーナドーナ いっしょにわるいことをしよう"
names = ["多娜多娜 一起来干坏事吧", "Dohna Dohna"]

[[aka]]
id = "Elden Ring"
names = ["艾尔登法环"]

[[aka]]
id = "ELDEN RING"
names = ["艾尔登法环"]

[[aka]]
id = "Elden Ring NightReign"
names = ["艾尔登法环：黑夜君临"]

[[aka]]
id = "ELDEN RING NIGHTREIGN"
names = ["艾尔登法环：黑夜君临", "黑环"]

[[aka]]
id = "ENDER LILIES: Quietus of the Knights"
names = ["终焉之莉莉：骑士寂夜"]

[[aka]]
id = "ENDER MAGNOLIA: Bloom in the Mist"
names = ["终焉之玛格诺利亚：雾中盛放之花"]

[[aka]]
id = "Escape the Backrooms"
names = ["逃离后室"]

[[aka]]
id = "Eternum"
names = ["永恒世界"]

[[aka]]
id = "Everlasting Summer"
names = ["永恒之夏"]

[[aka]]
id = "The Expanse: Osiris Reborn"
names = ["苍穹浩瀚：奥里西斯重生"]

[[aka]]
id = "Fate/Samurai Remnant"
names = ["FSR"]

[[aka]]
id = "Fate/stay night"
names = ["FSN"]

[[aka]]
id = "The Forest"
names = ["森林"]

[[aka]]
id = "(the) Gnorp Apologue"
names = ["糯米团子历代记"]

[[aka]]
id = "光明记忆：无限"
names = ["Bright Memory: Infinite"]

[[aka]]
id = "逆転裁判123 成歩堂セレクション"
names = ["逆转裁判123", "Phoenix Wright: Ace Attorney Trilogy"]

[[aka]]
id = "Hollow Knight"
names = ["空洞骑士"]

[[aka]]
id = "Hollow Knight: Silksong"
names = ["空洞骑士：丝之歌"]

[[aka]]
id = "How to Fish"
names = ["渔力全开"]

[[aka]]
id = "Human Fall Flat"
names = ["人类一败涂地"]

[[aka]]
id = "黑神话：悟空"
names = ["Black Myth: Wukong"]

[[aka]]
id = "It Takes Two"
names = ["双人成行"]

[[aka]]
id = "Kingdom Come: Deliverance II"
names = ["天国：拯救2"]

[[aka]]
id = "LAB-Still Alive"
names = []

[[aka]]
id = "Leap Year"
names = ["闰跃之年"]

[[aka]]
id = "Lethal Company"
names = ["致命公司"]

[[aka]]
id = "Liar's Bar"
names = ["骗子酒吧"]

[[aka]]
id = "LIMBO"
names = ["地狱边境"]

[[aka]]
id = "Limbus Company"
names = ["边狱巴士"]

[[aka]]
id = "Lobotomy Corporation - Monster Management Simulation"
names = ["脑叶公司"]

[[aka]]
id = "Machinarium"
names = ["机械迷城"]

[[aka]]
id = "Milk inside a bag of milk inside a bag of milk"
names = ["牛奶袋内袋装牛奶"]

[[aka]]
id = "Minecraft"
names = ["我的世界"]

[[aka]]
id = "Miside"
names = ["米塔"]

[[aka]]
id = "Monster Hunter: World"
names = ["怪物猎人：世界"]

[[aka]]
id = "Monument Valley"
names = ["纪念碑谷"]

[[aka]]
id = "Monument Valley 2"
names = ["纪念碑谷2"]

[[aka]]
id = "The Many Pieces of Mr. Coo"
names = ["裂开了！裤先生"]

[[aka]]
id = "谜月旅途"
names = ["Honeymoon : Mystery Journey"]

[[aka]]
id = "明末：渊虚之羽"
names = ["WUCHANG: Fallen Feathers"]

[[aka]]
id = "明日方舟"
names = ["Arknight"]

[[aka]]
id = "明日方舟：终末地"
names = ["Endfield"]

[[aka]]
id = "もんむす·くえすと！"
names = ["勇者大战魔物娘", "勇战"]

[[aka]]
id = "NieR: Automata"
names = ["尼尔：机械纪元", "尼尔：自动人形"]

[[aka]]
id = "NUKITASHI"
names = ["拔作岛"]

[[aka]]
id = "Ori and the Blind Forest"
names = ["奥日与黑暗森林"]

[[aka]]
id = "Outer Wilds"
names = ["星际拓荒"]

[[aka]]
id = "Persona 5 Royal"
names = ["女神异闻录5皇家版"]

[[aka]]
id = "Plants vs. Zombies: GOTY Edition"
names = ["植物大战僵尸：年度版"]

[[aka]]
id = "PUBG: BATTLEGROUNDS"
names = ["绝地求生", "吃鸡"]

[[aka]]
id = "R.E.P.O."
names = []

[[aka]]
id = "Rance Ⅸ -ヘルマン革命-"
names = ["兰斯9：赫尔曼革命"]

[[aka]]
id = "Rance Ⅹ -決戦-"
names = ["兰斯10：决战"]

[[aka]]
id = "Rance02 -反逆の少女たち-"
names = ["兰斯2：反叛的少女们"]

[[aka]]
id = "Rance03 -リーザス陥落-"
names = ["兰斯03：利萨斯陷落"]

[[aka]]
id = "Salt and Sanctuary"
names = ["盐与避难所"]

[[aka]]
id = "Sekiro: Shadows Die Twice"
names = ["只狼：影逝二度"]

[[aka]]
id = "SEQUEL blight"
names = ["凋零余波"]

[[aka]]
id = "Slay the Spire"
names = ["杀戮尖塔"]

[[aka]]
id = "Slay the Spire 2"
names = ["杀戮尖塔2"]

[[aka]]
id = "Snakebird Complete"
names = ["蛇鸟：完全版"]

[[aka]]
id = "Split Fiction"
names = ["双影奇境"]

[[aka]]
id = "Starbound"
names = ["星界边境"]

[[aka]]
id = "Stardew Valley"
names = ["星露谷物语"]

[[aka]]
id = "三色绘恋"
names = ["Tricolor Lovestory"]

[[aka]]
id = "社群审查"
names = ["The Censor"]

[[aka]]
id = "死神模拟器"
names = ["Trainee Death Simulator"]

[[aka]]
id = "Terraria"
names = ["泰拉瑞亚"]

[[aka]]
id = "Touhou Luna Nights"
names = ["东方月神夜"]

[[aka]]
id = "ツヴァイ!!2"
names = ["双星物语2"]

[[aka]]
id = "Ultimate Chicken Horse"
names = ["超级鸡马"]

[[aka]]
id = "Ultraman Fighting Evolution 3"
names = ["奥特曼格斗进化3"]

[[aka]]
id = "VA-11 Hall-A Cyberpunk Bartender Action"
names = ["赛博朋克酒保行动"]

[[aka]]
id = "Vampire Survivals"
names = ["吸血鬼幸存者"]

[[aka]]
id = "文字规则怪谈"
names = ["Myths of Rules"]

[[aka]]
id = "文字游戏"
names = ["Word Game"]

[[aka]]
id = "无限机兵"
names = ["AI LIMIT"]

[[aka]]
id = "犹格索托斯的庭院"
names = ["Yog-Sothoth's Yard"]

[[aka]]
id = "ZORT"
names = []

[[aka]]
id = "再见"
names = ["Once Again"]

[[aka]]
id = "ゼルダの伝説 ブレス オブ ザ ワイルド"
names = ["塞尔达传说 旷野之息", "The Legend of Zelda: Breath of the Wild", "野炊"]

