[aka]
"100% Orange Juice" = [
  "100%鲜橙汁",
]
"14种扫雷变体" = [
  "14 Minesweeper Variants",
]
"14种扫雷变体 2" = [
  "14 Minesweeper Variants 2",
]
"ACE COMBAT 7: SKIES UNKNOWN" = [
  "皇牌空战7：未知空域",
]
"AI: The Somnium Files" = [
  "AI：梦境档案",
]
"Alabaster Dawn" = [
  "皓白初晓",
]
"ANIMAL WELL" = [
  "动物井",
]
"Another Crab's Treasure" = [
  "蟹蟹寻宝奇遇",
]
"ARK: Survival Evolved" = [
  "方舟：生存进化",
]
"ARMORED CORE VI FIRES OF RUBICON" = [
  "装甲核心 VI 境界天火",
]
"Artis Impact" = [
  "爱氏物语",
]
"ASTLIBRA ～生きた証～ Revision" = [
  "神之天平",
]
"Axiom Verge" = [
  "公理边缘",
]
"爱与机器人维修技术" = [
  "All Our Broken Parts",
]
"穢翼のユースティア" = [
  "秽翼的尤斯蒂娅",
]
"アルミオシオンの医術師" = [
  "阿尔米奥西翁的医术师",
]
"Balatro" = [
  "小丑牌",
]
"Baldur's Gate 3" = [
  "博德之门3",
]
"Besiege" = [
  "围攻",
]
"The Binding of Isaac: Rebirth" = [
  "以撒的结合：重生",
]
"BLACK SOULS" = []
"BLACK SOULS -黒の童話と五魔姫-" = [
  "BLACK SOULS -黑童话与五魔姬-",
]
"Blasphemous" = [
  "神之亵渎",
]
"Blasphemous 2" = [
  "神之亵渎2",
]
"Bleak Sword DX" = [
  "荒绝之剑DX",
]
"Bloodstained: Ritual of the Night" = [
  "赤痕：夜之仪式",
]
"Bloodstained: The Scarlet Engagement" = [
  "赤痕：绯红誓约",
]
"被虐のノエル" = [
  "被虐的诺艾尔",
]
"媚肉の香り～ネトリネトラレヤリヤラレ～" = [
  "媚肉之香",
]
"CATO: Buttered Cat" = [
  "CATO 黄油猫",
]
"Celeste" = [
  "蔚蓝",
]
"Chants of Sennaar" = [
  "巴别塔圣歌",
]
"Cities: Skylines" = [
  "城市：天际线",
]
"Clair Obscur: Expedition 33" = [
  "光与影：33号远征队",
]
"COCOON" = [
  "茧",
]
"CODE VEIN" = [
  "噬血代码",
]
"Counter-Strike 2" = [
  "反恐精英2",
]
"Craft the World" = [
  "打造世界",
]
"Cris Tales" = [
  "水晶传说",
]
"CrossCode" = [
  "远星物语",
]
"Cultist Simulator" = [
  "密教模拟器",
]
"Cuphead" = [
  "茶杯头",
]
"Cyberpunk 2077" = [
  "赛博朋克 2077",
  "赛博朋克2077",
]
"苍翼：混沌效应" = [
  "BlazBlue Entropy Effect",
]
"草泥马历险记" = []
"DARK SOULS: REMASTERED" = [
  "黑暗之魂重制版",
]
"DARK SOULSⅡ: Scholar of the First Sin" = [
  "黑暗之魂2：原罪学者",
]
"Darkest Dungeon" = [
  "暗黑地牢",
]
"Dead Cells" = [
  "死亡细胞",
]
"Dead-End City: 死废城的少女" = [
  "Dead-End City Blues",
]
"戴森球计划" = [
  "Dyson Sphere Program",
]
"动物迷城" = [
  "Back to the Dawn",
]
"ダンガンロンパ3 -The End of 希望ヶ峰学園-" = [
  "新枪弹辩驳V3 大家自相残杀的新学期",
]
"ドーナドーナ いっしょにわるいことをしよう" = [
  "多娜多娜 一起来干坏事吧",
  "Dohna Dohna",
]
"Elden Ring" = [
  "艾尔登法环",
]
"ELDEN RING" = [
  "艾尔登法环",
]
"Elden Ring NightReign" = [
  "艾尔登法环：黑夜君临",
]
"ELDEN RING NIGHTREIGN" = [
  "艾尔登法环：黑夜君临",
  "黑环",
]
"ENDER LILIES: Quietus of the Knights" = [
  "终焉之莉莉：骑士寂夜",
]
"ENDER MAGNOLIA: Bloom in the Mist" = [
  "终焉之玛格诺利亚：雾中盛放之花",
]
"Escape the Backrooms" = [
  "逃离后室",
]
"Eternum" = [
  "永恒世界",
]
"Everlasting Summer" = [
  "永恒之夏",
]
"The Expanse: Osiris Reborn" = [
  "苍穹浩瀚：奥里西斯重生",
]
"Fate/Samurai Remnant" = [
  "FSR",
]
"Fate/stay night" = [
  "FSN",
]
"The Forest" = [
  "森林",
]
"(the) Gnorp Apologue" = [
  "糯米团子历代记",
]
"光明记忆：无限" = [
  "Bright Memory: Infinite",
]
"逆転裁判123 成歩堂セレクション" = [
  "逆转裁判123",
  "Phoenix Wright: Ace Attorney Trilogy",
]
"Hollow Knight" = [
  "空洞骑士",
]
"Hollow Knight: Silksong" = [
  "空洞骑士：丝之歌",
]
"How to Fish" = [
  "渔力全开",
]
"Human Fall Flat" = [
  "人类一败涂地",
]
"黑神话：悟空" = [
  "Black Myth: Wukong",
]
"It Takes Two" = [
  "双人成行",
]
"Kingdom Come: Deliverance II" = [
  "天国：拯救2",
]
"LAB-Still Alive" = []
"Leap Year" = [
  "闰跃之年",
]
"Lethal Company" = [
  "致命公司",
]
"Liar's Bar" = [
  "骗子酒吧",
]
"LIMBO" = [
  "地狱边境",
]
"Limbus Company" = [
  "边狱巴士",
]
"Lobotomy Corporation - Monster Management Simulation" = [
  "脑叶公司",
]
"Machinarium" = [
  "机械迷城",
]
"Milk inside a bag of milk inside a bag of milk" = [
  "牛奶袋内袋装牛奶",
]
"Minecraft" = [
  "我的世界",
]
"Miside" = [
  "米塔",
]
"Monster Hunter: World" = [
  "怪物猎人：世界",
]
"Monument Valley" = [
  "纪念碑谷",
]
"Monument Valley 2" = [
  "纪念碑谷2",
]
"The Many Pieces of Mr. Coo" = [
  "裂开了！裤先生",
]
"谜月旅途" = [
  "Honeymoon : Mystery Journey",
]
"明末：渊虚之羽" = [
  "WUCHANG: Fallen Feathers",
]
"明日方舟" = [
  "Arknight",
]
"明日方舟：终末地" = [
  "Endfield",
]
"もんむす·くえすと！" = [
  "勇者大战魔物娘",
  "勇战",
]
"NieR: Automata" = [
  "尼尔：机械纪元",
  "尼尔：自动人形",
]
"NUKITASHI" = [
  "拔作岛",
]
"Ori and the Blind Forest" = [
  "奥日与黑暗森林",
]
"Outer Wilds" = [
  "星际拓荒",
]
"Persona 5 Royal" = [
  "女神异闻录5皇家版",
]
"Plants vs. Zombies: GOTY Edition" = [
  "植物大战僵尸：年度版",
]
"PUBG: BATTLEGROUNDS" = [
  "绝地求生",
  "吃鸡",
]
"R.E.P.O." = []
"Rance Ⅸ -ヘルマン革命-" = [
  "兰斯9：赫尔曼革命",
]
"Rance Ⅹ -決戦-" = [
  "兰斯10：决战",
]
"Rance02 -反逆の少女たち-" = [
  "兰斯2：反叛的少女们",
]
"Rance03 -リーザス陥落-" = [
  "兰斯03：利萨斯陷落",
]
"Salt and Sanctuary" = [
  "盐与避难所",
]
"Sekiro: Shadows Die Twice" = [
  "只狼：影逝二度",
]
"SEQUEL blight" = [
  "凋零余波",
]
"Slay the Spire" = [
  "杀戮尖塔",
]
"Slay the Spire 2" = [
  "杀戮尖塔2",
]
"Snakebird Complete" = [
  "蛇鸟：完全版",
]
"Split Fiction" = [
  "双影奇境",
]
"Starbound" = [
  "星界边境",
]
"Stardew Valley" = [
  "星露谷物语",
]
"三色绘恋" = [
  "Tricolor Lovestory",
]
"社群审查" = [
  "The Censor",
]
"死神模拟器" = [
  "Trainee Death Simulator",
]
"Terraria" = [
  "泰拉瑞亚",
]
"Touhou Luna Nights" = [
  "东方月神夜",
]
"ツヴァイ!!2" = [
  "双星物语2",
]
"Ultimate Chicken Horse" = [
  "超级鸡马",
]
"Ultraman Fighting Evolution 3" = [
  "奥特曼格斗进化3",
]
"VA-11 Hall-A Cyberpunk Bartender Action" = [
  "赛博朋克酒保行动",
]
"Vampire Survivals" = [
  "吸血鬼幸存者",
]
"文字规则怪谈" = [
  "Myths of Rules",
]
"文字游戏" = [
  "Word Game",
]
"无限机兵" = [
  "AI LIMIT",
]
"犹格索托斯的庭院" = [
  "Yog-Sothoth's Yard",
]
"ZORT" = []
"再见" = [
  "Once Again",
]
"ゼルダの伝説 ブレス オブ ザ ワイルド" = [
  "塞尔达传说 旷野之息",
  "The Legend of Zelda: Breath of the Wild",
  "野炊",
]
