[[entry_ids]]
id = "ACE COMBAT 7: SKIES UNKNOWN"
files = ["ACE COMBAT 7- SKIES UNKNOWN"]

[[entry_ids]]
id = "AI: The Somnium Files"
files = ["AI- The Somnium Files"]

[[entry_ids]]
id = "Cities: Skylines"
files = ["Cities- Skylines"]

[[entry_ids]]
id = "Clair Obscur: Expedition 33"
files = ["Clair Obscur- Expedition 33", "Clair Obscur-Expedition 33"]

[[entry_ids]]
id = "DARK SOULS: REMASTERED"
files = ["DARK SOULS™-REMASTERED"]

[[entry_ids]]
id = "DARK SOULSⅡ: Scholar of the First Sin"
files = ["DARK SOULS™Ⅱ-Scholar of the First Sin"]

[[entry_ids]]
id = "Dead-End City: 死废城的少女"
files = ["Dead-End City- 死废城的少女"]

[[entry_ids]]
id = "ENDER LILIES: Quietus of the Knights"
files = ["ENDER LILIES- Quietus of the Knights"]

[[entry_ids]]
id = "ENDER MAGNOLIA: Bloom in the Mist"
files = ["ENDER MAGNOLIA- Bloom in the Mist"]

[[entry_ids]]
id = "The Expanse: Osiris Reborn"
files = ["The Expanse- Osiris Reborn"]

[[entry_ids]]
id = "Fate/Samurai Remnant"
files = ["Fate_Samurai Remnant"]

[[entry_ids]]
id = "Fate/stay night"
files = ["Fate_stay night"]

[[entry_ids]]
id = "光明记忆：无限"
files = ["光明记忆- 无限"]

[[entry_ids]]
id = "Hollow Knight: Silksong"
files = ["Hollow Knight- Silksong", "Hollow Knight-Silksong"]

[[entry_ids]]
id = "Kingdom Come: Deliverance II"
files = ["Kingdom Come- Deliverance II"]

[[entry_ids]]
id = "Monster Hunter: World"
files = ["Monster Hunter-World"]

[[entry_ids]]
id = "NieR: Automata"
files = ["NieR-Automata™"]

[[entry_ids]]
id = "Plants vs. Zombies: GOTY Edition"
files = ["Plants vs. Zombies- GOTY Edition"]

[[entry_ids]]
id = "PUBG: BATTLEGROUNDS"
files = ["PUBG-BATTLEGROUNDS"]

[[entry_ids]]
id = "Sekiro: Shadows Die Twice"
files = ["Sekiro™-Shadows Die Twice"]

