[tag_rows]
1 = [
  "ARPG",
  "类银河城",
  "平台跳跃",
  "指向点击",
  "策略",
  "视觉小说",
  "JRPG",
  "Rougelike",
  "塔防",
  "格斗",
  "沙盒",
  "二游",
  "AVG",
  "ACT",
  "RTS",
  "射击",
  "清版",
]
2 = [
  "模拟经营",
  "像素",
  "回合制",
  "解谜",
  "类魂",
  "卡牌",
  "箱庭",
  "剧情",
  "线性",
  "养成",
]
3 = [
  "Metagame",
  "放置",
  "末日",
  "物理",
  "派对",
  "知识锁",
]

[tag_aliases]
"类银恶" = "类银河城"
"SLG" = "策略"
"冒险" = "AVG"
"动作" = "ACT"
"即时战略" = "RTS"
"FPS" = "射击"
"TPS" = "射击"
